/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbol;

import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El-Afiandy
 */
public class FormBooking extends javax.swing.JFrame {

    /**
     * Creates new form FormBooking
     */
    public FormBooking() {
        initComponents();
        tampil();
        bersih();
        setDefaultTabel();
    }
    
   
    private void bersih(){
        namapemesan.setText("");
        notelpemesan.setText("");
        jenisps.setSelectedItem(0);
        jaminan.setSelectedItem(0);
        tglbooking.setText("");
        tglbalik.setText("");
        tglbalik.setEnabled(false);
        alamatpemesan.setText("");
        btnBooking.setText("Booking");
        
    }
    
     public void setDefaultTabel(){ 
        String stat = "";  
        String[] colom={"Kode Booking", "Nama Pemesan", "No Telp", "Jenis PS","Jaminan","Tanggal Booking","Tanggal Kembali","Alamat"};
        tblModel.setDataVector(null, colom);
        jTable2.setModel(tblModel);  
        Tabel(jTable2,new int[]{100,300,75,75,75,200,200,400});
       // cekdb();
        try { 
            Class.forName(MainMenu.driver); 
            Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass); 
            Statement  stt = konek.createStatement(); 
            String     str="Select * from tbbooking"; 
            ResultSet  res =  stt.executeQuery(str); 
            
            while (res.next()) { 
                tblModel.addRow(new Object[]{
                res.getString("kd_booking"),
                res.getString("nama_pemesan"), 
                res.getString("no_telp"), 
                res.getString("jenis_ps"),
                res.getString("jaminan"),
                res.getString("tgl_booking"),
                res.getString("tgl_kembali"),
                res.getString("alamat"),
                //res.getString(""),
                //Object [] data={Kd, nm, Al, kt}; 
                //tblModel.addRow(data); 
            });
            } 
            res.close(); 
            stt.close(); 
            konek.close(); 
        } catch(Exception exc){ 
            System.err.println(exc.getMessage()); 
            JOptionPane.showMessageDialog(null, exc); 
        }
     }
     private void Tabel (javax.swing.JTable tb, int lebar[]) { 
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        int kolom=tb.getColumnCount(); 
        for (int i=0;i < kolom; i++){ 
            javax.swing.table.TableColumn tbc =tb.getColumnModel().getColumn(i); 
            tbc.setPreferredWidth(lebar[i]); 
            tb.setRowHeight(17); 
        } 
    } 
  //Mengatur tampilan caption pada data grid   
    private javax.swing.table.DefaultTableModel getDefaultTableModel () { 
        return new javax.swing.table.DefaultTableModel( 
                new Object[] []{}, 
                new String [] {"Kode Booking", "Nama Pemesan", "No Telp", "Jenis PS","Jaminan","Tanggal Booking","Tanggal Kembali","Alamat"} 
        ){ 
            boolean [] canEdit= new boolean [] { 
                false, false, false, false, false, false, false, false 
         }; 
            @Override 
            public boolean isCellEditable (int rowIndex, int columnIndex){ 
                    return canEdit[columnIndex]; 
             } 
         }; 
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        namapemesan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        notelpemesan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenisps = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        alamatpemesan = new java.awt.TextArea();
        btnBooking = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jaminan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tglbooking = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tglbalik = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama");

        namapemesan.setText("jTextField1");

        jLabel3.setText("No Telp");

        notelpemesan.setText("jTextField2");

        jLabel4.setText("Jenis PS");

        jLabel5.setText("Alamat");

        btnBooking.setText("Booking");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        jLabel6.setText("Jaminan");

        jaminan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KTP", "SIM", "KTM" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setText("Tgl Booking");

        tglbooking.setText("jTextField1");
        tglbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbookingActionPerformed(evt);
            }
        });

        jLabel8.setText("Tgl Balik");

        tglbalik.setText("jTextField2");

        jLabel10.setText("Tampil Pemesanan");

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 100));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Roney PlayStation");

        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rental PS 2,PS 3,PS 4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jaminan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(namapemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(notelpemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tglbooking)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tglbalik, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jenisps, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alamatpemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namapemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(notelpemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jenisps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jaminan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tglbooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tglbalik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(alamatpemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBooking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        if(btnBooking.getText()=="Booking"){
            try { 
                Class.forName(MainMenu.driver); 
               Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass);
               Statement stt = konek.createStatement(); 
               String str = "Insert into tbbooking (nama_pemesan,no_telp,jenis_ps,jaminan,tgl_booking,alamat) values ('"
                       +namapemesan.getText()+"', '"+notelpemesan.getText()+"', '"+jenisps.getSelectedItem().toString()
                       +"', '"+jaminan.getSelectedItem().toString()+"', '" +tglbooking.getText()+"', '"
                       +alamatpemesan.getText()+"')";
               stt.execute(str); 
               stt.close(); 
           } catch(Exception exc){ 
               System.err.println(exc.getMessage()); 
               JOptionPane.showMessageDialog(null, exc); 
           }
        }else{
            //int pesan,kembali,bayar,total;
            //DefaultTableModel tm=(DefaultTableModel) jTable2.getModel();
        //long pesan=Date.parseInt(tglbooking.getText());
        //long kembali=Date.parseInt(tglbalik.getText());
        //bayar=integer.parseInt(tTotal.getText());
        //total=kembali-pesan;
        //int harga = 0, totalBayar =0;
        //tTotal.setText(String.valueOf(total));
    //    long balim = Date.parse(tglbalik.getText());
      //  long book = Date.parse(tglbooking.getText());
        //long total = balim-book;
        //int harga = 0, totalBayar =0;
    
          int respon=JOptionPane.showConfirmDialog(null, "Data sudah benar?", "Konfirmasi", 
          JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); 
        //JOptionPane.showMessageDialog(null, String.valueOf(total));
        //} catch (ExceptionInInitializerError e) {
        //System.err.println(e.getMessage()); 
        //}
            
            if (respon==JOptionPane.YES_OPTION){ 
            try { 
               Class.forName(MainMenu.driver); 
            Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass);
            Statement stt = konek.createStatement();   
            String str = "update tbbooking set tgl_kembali='"+tglbalik.getText()+"' where nama_pemesan='"
                    +namapemesan.getText()+"'";
            stt.execute(str); 
            stt.close();
           } catch(Exception exc){ 
               System.err.println(exc.getMessage()); 
               JOptionPane.showMessageDialog(null, exc); 
           } 
           }
        }
        bersih(); 
        setDefaultTabel();
    }//GEN-LAST:event_btnBookingActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int i=jTable2.getSelectedRow();
        namapemesan.setText(tblModel.getValueAt(i, 1).toString());
        notelpemesan.setText(tblModel.getValueAt(i, 2).toString());
        jenisps.setSelectedItem(tblModel.getValueAt(i, 3).toString());
        jaminan.setSelectedItem(tblModel.getValueAt(i, 4).toString());
        tglbooking.setText(tblModel.getValueAt(i, 5).toString());
        alamatpemesan.setText(tblModel.getValueAt(i, 7).toString());
        
        tglbalik.setEnabled(true);  
        btnBooking.setText("Lunas");
    }//GEN-LAST:event_jTable2MouseClicked

    private void tglbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglbookingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea alamatpemesan;
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jaminan;
    private javax.swing.JComboBox<String> jenisps;
    private javax.swing.JTextField namapemesan;
    private javax.swing.JTextField notelpemesan;
    private javax.swing.JTextField tglbalik;
    private javax.swing.JTextField tglbooking;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTableModel();

    private void tampil() {
        try { 
            Class.forName(MainMenu.driver); 
            Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass); 
            Statement  stt = konek.createStatement(); 
            String     str="Select * from tbmasterps"; 
            ResultSet  res =  stt.executeQuery(str); 
            
            while (res.next()){
                jenisps.addItem(res.getString("jenis_ps"));
            }
            res.close(); 
            stt.close(); 
            konek.close(); 
        } catch(Exception exc){ 
            System.err.println(exc.getMessage()); 
            JOptionPane.showMessageDialog(null, exc); 
        }
    }
    
}
