/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbol;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Hanif-Nisrina
 */
public class FormMasterPs extends javax.swing.JFrame {
/*    koneksi dbsetting;
    String driver, database, user, pass, namadb, portdb; 
    
    public void cekdb(){
        dbsetting = new koneksi(); 
        driver = dbsetting.SettingPanel("dbdriver"); 
        database = dbsetting.SettingPanel("dbdata"); 
        user = dbsetting.SettingPanel("dbuser"); 
        pass = dbsetting.SettingPanel("dbpass"); 
        namadb=dbsetting.SettingPanel("dbnama"); 
        portdb=dbsetting.SettingPanel("dbport"); 
        database=database+':'+portdb+'/'+namadb; 
    }*/
    

    /**
     * Creates new form FrmRoom
     */
    public FormMasterPs() {
        initComponents();
        bersih();
        setDefaultTabel();
    }
    
   
    private void bersih(){
        txtharga.setText("0");
        txtkode.setText("");
        Jcb.setSelectedItem(0);
        btnsimpan.setText("Simpan");
    }
    
     public void setDefaultTabel(){ 
        String stat = "";  
        String[] colom={"Kode", "Nama", "Harga"};
        tblModel.setDataVector(null, colom);
        jTable1.setModel(tblModel);  
        
        Tabel(jTable1,new int[]{100,300,75,50});
       // cekdb();
        try { 
            Class.forName(MainMenu.driver); 
            Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass); 
            Statement  stt = konek.createStatement(); 
            String     str="Select * from tbmasterps"; 
            ResultSet  res =  stt.executeQuery(str); 
            
            while (res.next()) { 
                tblModel.addRow(new Object[]{
                res.getString("kdps"),
                res.getString("jenis_ps"), 
                res.getString("harga"), 
               
                //Object [] data={Kd, nm, Al, kt}; 
                //tblModel.addRow(data); 
            });
            } 
            res.close(); 
            stt.close(); 
            konek.close(); 
        } catch(Exception exc){ 
            System.err.println(exc.getMessage()); 
            JOptionPane.showMessageDialog(null, exc); 
        } 
    } 
     
     private void Tabel (javax.swing.JTable tb, int lebar[]) { 
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); 
        int kolom=tb.getColumnCount(); 
        for (int i=0;i < kolom; i++){ 
            javax.swing.table.TableColumn tbc =tb.getColumnModel().getColumn(i); 
            tbc.setPreferredWidth(lebar[i]); 
            tb.setRowHeight(17); 
        } 
    } 
  //Mengatur tampilan caption pada data grid   
    private javax.swing.table.DefaultTableModel getDefaultTableModel () { 
        return new javax.swing.table.DefaultTableModel( 
                new Object[] []{}, 
                new String [] {"Kode", "Nama", "Harga"} 
        ){ 
            boolean [] canEdit= new boolean [] { 
                false, false, false, false 
         }; 
            @Override 
            public boolean isCellEditable (int rowIndex, int columnIndex){ 
                    return canEdit[columnIndex]; 
             } 
         }; 
    } 
         
    /**
     * This method is called from within the constrctor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btntutup = new javax.swing.JButton();
        Jcb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Room");
        setAutoRequestFocus(false);

        jLabel1.setText("Kode PS");

        jLabel2.setText("Jenis PS");

        jLabel3.setText("Harga");

        txtkode.setText("jTextField1");

        txtharga.setText("jTextField3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnsimpan.setText("jButton1");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btntutup.setText("Tutup");
        btntutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntutupActionPerformed(evt);
            }
        });

        Jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PS 2", "PS 3", "PS 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btntutup))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnhapus)
                    .addComponent(Jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btntutup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(btnsimpan.getText()=="Simpan"){
            try { 
               Class.forName(MainMenu.driver); 
               Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass);
               Statement  stt = konek.createStatement(); 
               String     str = "Insert into tbmasterps (kdps, jenis_ps, harga) values ('"+txtkode.getText()+"', '"+Jcb.getSelectedItem().toString()+"', '" +txtharga.getText()+"')"; 
               stt.execute(str); 
               stt.close(); 
           } catch(Exception exc){ 
               System.err.println(exc.getMessage()); 
               JOptionPane.showMessageDialog(null, exc); 
           }
        }else{
            int respon=JOptionPane.showConfirmDialog(null, "Data sudah benar?", "Konfirmasi", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); 
            if (respon==JOptionPane.YES_OPTION){ 
            try { 
               Class.forName(MainMenu.driver); 
               Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass); 
               Statement  stt = konek.createStatement(); 
               String     str = "update TBMASTERPS  set jenis_ps='"+Jcb.getSelectedItem().toString()+"', harga='"+txtharga.getText()+"'  where kdps='"+txtkode.getText()+"'"; 
               stt.execute(str); 
               stt.close(); 
               konek.close(); 
           } catch(Exception exc){ 
               System.err.println(exc.getMessage()); 
               JOptionPane.showMessageDialog(null, exc); 
           } 
           }
        }
        bersih(); 
        setDefaultTabel(); 
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i=jTable1.getSelectedRow();
        txtkode.setText(tblModel.getValueAt(i, 0).toString());
        Jcb.setSelectedItem(tblModel.getValueAt(i, 1).toString());
        txtharga.setText(tblModel.getValueAt(i, 2).toString());
        btnsimpan.setText("Rubah");
    }//GEN-LAST:event_jTable1MouseClicked

    private void btntutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntutupActionPerformed
        dispose();
    }//GEN-LAST:event_btntutupActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try { 
               Class.forName(MainMenu.driver); 
               Connection konek = DriverManager.getConnection(MainMenu.database, MainMenu.user, MainMenu.pass); 
               Statement  stt = konek.createStatement(); 
               String     str = "delete from tbmasterps  where kdps='"+txtkode.getText()+"'"; 
               stt.execute(str); 
               stt.close(); 
               konek.close(); 
           } catch(Exception exc){ 
               System.err.println(exc.getMessage()); 
               JOptionPane.showMessageDialog(null, exc); 
           }
        bersih();
        setDefaultTabel();
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMasterPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMasterPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMasterPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMasterPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMasterPs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jcb;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTableModel();
    }