/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbol;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import java.io.*;
import java.util.*;
import java.sql.*;

/**
 *
 * @author Hanif-Nisrina
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        //membuat satu layar penuh
        setExtendedState(MAXIMIZED_BOTH);
        //mengisikan variabel untuk koneksi ke daatabase
        dbsetting = new Database();        
        driver = dbsetting.SettingPanel("dbdriver");        
        database = dbsetting.SettingPanel("dbdata");        
        user = dbsetting.SettingPanel("dbuser");        
        pass = dbsetting.SettingPanel("dbpass");        
        namadb = dbsetting.SettingPanel("dbnama");        
        portdb = dbsetting.SettingPanel("dbport");        
        database = database + ':' + portdb + '/' + namadb;
        tutupmenu();
        koneksi();
    }
    
    public void buka() {
        for (int i = 0; i < jMenuBar1.getMenuCount() - 1; i++) {
            jMenuBar1.getMenu(i).setVisible(true);
        }
    }
    
    public void hakakses(int i) {
        //JOptionPane.showMessageDialog(null, Integer.toString(i));
        switch (i) {
            case 1:
                mnRoom.setVisible(true);
                break;
            case 2:
                mnbooking.setVisible(true);
                break;
            case 3:
                mndatabase.setVisible(true);
                break;
            case 7:
                MnHakakses.setVisible(true);
            default:
                System.out.println("");
        }
        MnLogin.setText("Log Out");
    }
    
    public void koneksi() {
        try {            
            Class.forName(driver);            
            Connection konek = DriverManager.getConnection(database, user, pass);
            //Statement  stt = konek.createStatement(); 
        } catch (Exception exc) {            
            int respon = JOptionPane.showConfirmDialog(null, "Database Tidak Ditemukan!, "
                    + "Konfigurasi Ulang", "Kesalahan",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);            
            if (respon == JOptionPane.YES_OPTION) {                
                try {                    
                    frmsettingdb n = new frmsettingdb();
                    n.setLocationRelativeTo(null);
                    n.setVisible(true);
                } catch (Exception exc1) {                    
                    System.exit(0);                    
                }
            }
        }
        
    }
    
    private void tutupmenu() {
        for (int i = 0; i < jMenuBar1.getMenuCount() - 1; i++) {
            jMenuBar1.getMenu(i).setVisible(false);
            for (int a = 0; a < jMenuBar1.getMenu(i).getItemCount() - 1; a++) {
                jMenuBar1.getMenu(i).getItem(a).setVisible(false);                
            }
        }
        MnLogin.setText("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnRoom = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnbooking = new javax.swing.JMenuItem();
        MnPengaturan = new javax.swing.JMenu();
        mndatabase = new javax.swing.JMenuItem();
        mnhakakses = new javax.swing.JMenuItem();
        MnHakakses = new javax.swing.JMenu();
        MnLogin = new javax.swing.JMenuItem();
        mntutup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Roney PlayStation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jMenu1.setText("Master");
        jMenu1.setName("mnmaster"); // NOI18N

        mnRoom.setText("PS");
        mnRoom.setName("mnroom"); // NOI18N
        mnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRoomActionPerformed(evt);
            }
        });
        jMenu1.add(mnRoom);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenu2.setName("mntrans"); // NOI18N

        mnbooking.setText("Pemesanan");
        mnbooking.setName("mnbookinb"); // NOI18N
        mnbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbookingActionPerformed(evt);
            }
        });
        jMenu2.add(mnbooking);

        jMenuBar1.add(jMenu2);

        MnPengaturan.setText("Pengaturan");

        mndatabase.setText("Database");
        mndatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndatabaseActionPerformed(evt);
            }
        });
        MnPengaturan.add(mndatabase);

        mnhakakses.setText("Hak Akses");
        mnhakakses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnhakaksesActionPerformed(evt);
            }
        });
        MnPengaturan.add(mnhakakses);

        jMenuBar1.add(MnPengaturan);

        MnHakakses.setText("Pengguna");

        MnLogin.setText("Login");
        MnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLoginActionPerformed(evt);
            }
        });
        MnHakakses.add(MnLogin);

        mntutup.setText("Tutup");
        mntutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntutupActionPerformed(evt);
            }
        });
        MnHakakses.add(mntutup);

        jMenuBar1.add(MnHakakses);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRoomActionPerformed
        FormMasterPs n = new FormMasterPs();
        n.setLocationRelativeTo(null);
        n.setVisible(true);
    }//GEN-LAST:event_mnRoomActionPerformed

    private void mndatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndatabaseActionPerformed
        frmsettingdb n = new frmsettingdb();
        n.setLocationRelativeTo(null);        
        n.setVisible(true);
    }//GEN-LAST:event_mndatabaseActionPerformed

    private void MnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLoginActionPerformed
        if (MnLogin.getText() == "Login") {
            FrmLogin n = new FrmLogin();
            n.setLocationRelativeTo(null);
            n.setVisible(true);
            this.dispose();
        } else {
            tutupmenu();
        }
    }//GEN-LAST:event_MnLoginActionPerformed

    private void mnhakaksesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnhakaksesActionPerformed
        FrmSettingUser n = new FrmSettingUser();
        n.setLocationRelativeTo(null);
        n.setVisible(true);
    }//GEN-LAST:event_mnhakaksesActionPerformed

    private void mntutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntutupActionPerformed
        int respon=JOptionPane.showConfirmDialog(null, "Prograam Akan ditutup?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respon==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mntutupActionPerformed

    private void mnbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbookingActionPerformed
        // TODO add your handling code here:
        FormBooking pes=new FormBooking();
        pes.setLocationRelativeTo(null);
        pes.setVisible(true);
    }//GEN-LAST:event_mnbookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnHakakses;
    private javax.swing.JMenuItem MnLogin;
    private javax.swing.JMenu MnPengaturan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnRoom;
    private javax.swing.JMenuItem mnbooking;
    private javax.swing.JMenuItem mndatabase;
    private javax.swing.JMenuItem mnhakakses;
    private javax.swing.JMenuItem mntutup;
    // End of variables declaration//GEN-END:variables
   
    Database dbsetting;
    
    public static String driver, database, user, pass, namadb, portdb;
}
